### PR TITLE
User Authentication with Django

### PR DESCRIPTION
**Pull request by SubhradeepSS**
Issue solved: #5 

Features added:

- Signup and Login Page using Bootstrap (Redirect to Login and Signup links added respectively)

- User Signup using Username, Password and Email (error message popup if user already exists with entered username)

- User Login using Username and Password (error message popup if invalid credentials are entered)

- User logout

### CODE REVIEW

**Comment by diyajaiswal11** [comment]
> Issue solved: #5
> 
> Features added:
> 
> * Signup and Login Page using Bootstrap (Redirect to Login and Signup links added respectively)
> * User Signup using Username, Password and Email (error message popup if user already exists with entered username)
> * User Login using Username and Password (error message popup if invalid credentials are entered)

Hey @SubhradeepSS , can you please share the screenshots here so that I can review easily?

**Comment by SubhradeepSS** [comment]
Login
Login_WrongCredentials
Signup
SIgnup_Error
Home

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 I have added some screenshots of login,signup page(including error messages popping) and also home page having the logout option in navbar.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 I have added some screenshots of login,signup page(including error messages popping) and also home page having the logout option in navbar.

Good job !! @SubhradeepSS :)

**Pull request merged**
