### PR TITLE
[Fixes #15] Added social authentication

### LINKED ISSUE #15: Add Social Authentication
User should have an option of signing up using his Facebook and Google accounts.

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
fixes #15 
Capture2

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 Please review my pr.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Please review my pr.

Hey I wanted social auth using Google and Facebook accounts, not Github. Please make the changes and attach the screenshots of the working of the same.

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 the link is not working for google login. Please guide me.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 the link is not working for google login. Please guide me.

What is the issue that you're facing?

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 we need to create api keys which are not working it is showing page not found

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 we need to create api keys which are not working it is showing page not found

Did you create API Keys?

**Comment by Vrindagupta6828** [comment]
Yes but still the redirect url is not working

**Comment by jaymes15** [comment]
https://realpython.com/adding-social-authentication-to-django/

@Vrindagupta6828  you can use this as a guide

**Pull request closed without merging**
