### PR TITLE
Adding update profile feature

### LINKED ISSUE #19: Add Update Profile option for users.
Logged in user should have a update profile option where he can add his profile picture and update his username or email. (Make sure that the username and email is unique even after updating profile.)

- Write templates, views, URLs for the same and also update profile in navbar of home page.

### PR DESCRIPTION
**Pull request by Halix267**
closes #19 
Adding update profile feature

### CODE REVIEW

**Comment by Halix267** [comment]
@diyajaiswal11 .Plzz review it

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 .Plzz review it

Please attach screenshots of the same and resolve the merge conflicts.

**Comment by Halix267** [comment]
@diyajaiswal11  how can i ressolve conflicts bcz it is saying that only those files with write acces can merge pull requests
..Plzz guide me

**Comment by Halix267** [comment]
Screenshot from 2020-12-11 09-08-25

Screenshot from 2020-12-11 09-08-45

Screenshot from 2020-12-11 09-09-27

Screenshot from 2020-12-11 09-09-45

**Comment by Halix267** [comment]
@diyajaiswal11 Plzz review it

**Review by diyajaiswal11 — COMMENTED** [review]
Great work @Halix267

**Pull request merged**
