### PR TITLE
close#1

### PR DESCRIPTION
**Pull request by yashgautam9274**
Adding Search option in nav bar

### CODE REVIEW

**Comment by diyajaiswal11** [comment]
> Adding Search option in nav bar

Hey @yashgautam9274 , you have not written the views function. Do refer [https://github.com/diyajaiswal11/Bloggitt/issues/1#issuecomment-734933456](this) and make the changes.

**Comment by yashgautam9274** [comment]
I don't know how to solve this issue

**Comment by diyajaiswal11** [comment]
> I don't know how to solve this issue

Do you have basic idea of Django?? @yashgautam9274

**Comment by yashgautam9274** [comment]
no i know only  html ,css,python,little php

**Comment by diyajaiswal11** [comment]
> no i know only html ,css,python,little php

Would you like to work on this issue? I can send some links where you can refer how to solve this issue.

**Comment by yashgautam9274** [comment]
ok
i want to work on your readme file . i can added code of conductance , contibution guidelines file and link them in readme.md and many other beautiful thing in u readme file

**Comment by diyajaiswal11** [comment]
> ok
> i want to work on your readme file . i can added code of conductance , contibution guidelines file and link them in readme.md and many other beautiful thing in u readme file

Okay!!

**Pull request closed without merging**
