### PR TITLE
[Fixes #6] Added pagination

### LINKED ISSUE #6: Add Pagination
Add Pagination on the index.html page and display 10 blogs per page.

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
fixes #6

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 Please review my PR.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Please review my PR.

Hey @Vrindagupta6828 , please share the screenshot of the pagination part.

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 When I ran the server the page is not showing any place to write blogs so how can I show pagination. When blogs will be added then only then pagination will be visible. Please guide me regarding the same.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 When I ran the server the page is not showing any place to write blogs so how can I show pagination. When blogs will be added then only then pagination will be visible. Please guide me regarding the same.

Yes @Vrindagupta6828 , uploading posts from home page has not been added yet. For testing purpose you can create few posts from admin.

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 ok i will try

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 It is showing error

**Comment by Vrindagupta6828** [comment]
will create another clean one

**Pull request closed without merging**
