### PR TITLE
[Fixes #7] Added category for blogs

### LINKED ISSUE #7: Add Category option in Blogs
Add categories for blogs. List of categories are:
- Programming/Technology
- Health/Fitness
- Personal
- Fashion 
- Food
- Travel
- Business
- Art
- Other

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
fixes #7

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 Please review my pr.
category
This is the screenshot for the same

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Please review my pr.
> category
> This is the screenshot for the same

Good job!! @Vrindagupta6828

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 Can you please tell me when will i get points for the same?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Can you please tell me when will i get points for the same?

I have updated the points for all the merged pull requests in my project, You can check now.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Can you please tell me when will i get points for the same?

@Vrindagupta6828 , I've updated the points for all merged PRs in my project. You can check now.

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 I am sorry but I didn't understand i should remove the foreign key and the categories model and should just add a single line in post model? How will that select from the category. The changes i have done is doing the same.

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 For a dropdown list of categories we need a foreign key

**Comment by Vrindagupta6828** [comment]
category 2
It would be like this.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 For a dropdown list of categories we need a foreign key

Refer [this](https://www.geeksforgeeks.org/how-to-use-django-field-choices/), it will display a lis tof choices.

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 so i should make a new branch for it?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 so i should make a new branch for it?

Yes make a new branch, and make a PR for the same.

**Comment by Vrindagupta6828** [comment]
Ok sure

**Pull request merged**
