### PR TITLE
[Fixes #6] Added Pagination

### LINKED ISSUE #6: Add Pagination
Add Pagination on the index.html page and display 10 blogs per page.

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
fixes #6

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 Please review my pr.

**Comment by Vrindagupta6828** [comment]
page1
page2
In case you need screenshots.

**Comment by diyajaiswal11** [comment]
> page1
> page2
> In case you need screenshots.

Good work!! @Vrindagupta6828

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 Please update my points

**Pull request merged**
